version: "3.7"

services:
  web:
    image: "traceabilityweb:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      PORT: 80
      NODE_ENV: "production"
    ports:
      - target: 80
        published: 8007
        mode: host
