export const API = {
  LOGIN: "/api/v2/users/login",
  USERS: "/user/myInfo",
  USER_DA_XOA: "/nguoi-dung/daxoa",
  USER_DA_XOA_ID: "/nguoi-dung/daxoa/{0}",
  USER_ID: "/user/{0}",
  MY_INFO: "/api/v2/users/me",
  UPDATE_MY_INFO: "/api/v2/users/me",
  DASHBOARD: "/api/dashboard",
  FILE: "/api/file",
  FILE_ID: "/api/file/{0}",
  FILE_NAME_ID: "/api/file/?id={0}&file_name={1}",
  PREVIEW_ID: "/api/v2/files/preview/{0}",
  ASSIGN_STATUS: "/api/trangthaiphieugiaoviec",
  ROLE: "/api/role",
  ROLE_ID: "/api/role/{0}",
  DETAIL: "/api/noidungdanhgia",
  DETAIL_ID: "/api/noidungdanhgia/{0}",
  SETTING: "/api/cai-dat-he-thong",
  SETTING_ID: "/api/cai-dat-he-thong/{0}",
  USER_RESET_PASSWORD: "/api/v2/users/reset-password",
  USER_CHANGE_PASSWORD: "/api/nguoi-dung/change-password",
  USER_FORGET_PASSWORD: "/api/v2/users/forgot-password-mail",
  NOTIFICATION: "/api/v2/notification",
  NOTIFICATION_ID: "/api/notification/{0}",
  PARCEL_BY_ID: "/api/v2/parcel/{0}",
  PARCEL_BY_NAME: "/api/v2/parcel/find/{0}",
  QUERY_PRODUCT_BY_PARCEL_NAME: "/api/v2/parcel/find",
  QUERY_PRODUCT_BY_PARCEL_NAME_NOT_PUBLIC: "/api/v2/parcel/find-by-name",
  GET_LIST_PROCEDURE: "/api/v2/procedure",
  GET_TEMPLETE_PROCEDURE_BY_ID: "/api/v2/procedure/{0}",
  GET_PROCESS_TEMPLETE_PROCEDURE_BY_ORG:
    "/api/v2/template-step?limit={0}&procedure={1}",
  REMOVE_PROCEDURE_BY_ID: "/api/v2/procedure/{0}",
  CREATE_PROCEDURE: "/api/v2/procedure",
  CREATE_TEMPLATE_STEP_PROCEDURE: "/api/v2/template-step",
  EDIT_PROCEDURE: "/api/v2/procedure/{0}",
  EDIT_TEMPLATE_STEP: "/api/v2/template-step/{0}",
  GET_PROCEDURE_BY_ORG: "/api/v2/procedure/by-my-org?page={0}&limit={1}{2}",
  GET_ORG_UNIT: "/api/v2/org-unit?page={0}&limit={1}{2}",
  UPLOAD_IMAGE: "/api/v2/files",
  CHANGE_MY_AVATAR: "/api/v2/users/avatar",
  CHANGE_PASSWORD: "/api/v2/users/change-password",
  ENROLL: "/api/v2/pki",
  UPDATE_TITLE_KEY_MY_SELF: "/api/v2/pki/me",
  PRODUCT_GET_BY_MY_ORG: "/api/v2/product/by-my-org-contain-parcels",
  GET_LIST_ORG: "/api/v2/org",
  GET_SELECT_PARCEL_BY_MY_ORG: "/api/v2/procedure/my-org-procedure-names",
  GET_PARCEL_BY_PRODUCT: "/api/v2/parcel/by-product",
  GET_USER_BY_ORG: "/api/v2/users/by-my-org",
  REGISTER: "/api/v2/users",
  GET_STEP_BY_PROCEDURE: "/api/v2/template-step/by-procedure",
  GET_MEDIA_BY_PROCEDURE: "/api/v2/media/by-procedure",
  GET_MEDIA_BY_STEP: "/api/v2/media/by-step",
  GET_STEP_BY_PARCEL: "/api/v2/step/by-parcel",
  GET_STEP_BY_PARCEL_ID: "/api/v2/step/by-parcel/{0}",
  ADD_STEP: "/api/v2/step",
  EDIT_STEP: "/api/v2/step/{0}",
  GET_ORG_BY_ID: "/api/v2/org/{0}",
  DELETE_ALL_PARCEL: "/api/v2/step/delete-by-parcel/{0}",
  //Phân quyền vai trò
  PHAN_QUYEN_VAI_TRO: "/api/v2/roles",
  PHAN_QUYEN_VAI_TRO_QUERY: "/api/v2/roles/by-my-org?page={0}&limit={1}{2}",
  PHAN_QUYEN_VAI_TRO_ID: "/api/v2/roles/{0}",
  VAI_TRO_TRANG_ID: "api/v2/roles/{0}/trang/{1}",
  VAI_TRO_TRANG: "api/v2/roles/{0}/trang",
  ADD_NEW_PRODUCT: "/api/v2/product",
  UPLOAD_FILE: "/api/v2/files/files",
  ADD_MEDIA_TO_TABLE: "/api/v2/media",
  GET_PRODUCT_BY_ID_BASE: "/api/v2/product/{0}",
  GET_MEDIA_BY_ID: "/api/v2/media/by-product",
  DOWNLOAD_FILE: "/api/v2/files/preview",
  DELETE_FILE_BY_FILE_NAME: "/api/v2/files/{0}",
  DELETE_MEDIA_BY_ID: "/api/v2/media/{0}",
  REGISTER: "/api/v2/users",
  GET_LIST_BROWSER: "/api/v2/users/list-browser-my-org",
  SENT_TO_BROWSER: "/api/v2/step/send-to-browsers",
  SENT_TO_BROWSER_IN_ENDORSER: "/api/v2/step/send-to-browsers-in-endorser",
  LIST_BROWSER: "/api/v2/org/list-endorser",
  SENT_TO_ENDORSER: "/api/v2/step/send-to-endorsers",
  GET_LIST_ENDORSER: "/api/v2/users/list-endorser",
  SENT_RESULT_TO_PRODUCER:
    "/api/v2/lifecycle-inspection/send-result-inspection",
  // Quản lý nhân viên
  GET_MY_ORG_USERS: "/api/v2/users/by-my-org?page={0}&limit={1}{2}",
  GET_MY_ORG_ROLES: "/api/v2/roles/by-my-org?page={0}&limit={1}{2}",
  ISSUE_ACCOUNT: "/api/v2/users/issue-account",
  USERS_BY_ID: "/api/v2/users/{0}",
  // Quản lý tài khoản tổ chức
  GET_INACTIVE_ORG: "/api/v2/users/inactive?page={0}&limit={1}{2}",
  ISSUE_ACCOUNT_ORG: "/api/v2/users/issue-account-org",

  //Quản lý kiểm định
  GET_MY_ORG_INSPECTS_BY_PARCEL:
    "/api/v2/step/my-org-inspects-by-pracel?page={0}&limit={1}{2}",
  CHANGE_INSPECTOR: "/api/v2/step/change-inspector/{0}",
  CHANGE_INSPECTOR_ALL: "/api/v2/step/change-inspectors",
  GET_MY_INSPECTS: "/api/v2/step/my-inspects?page={0}&limit={1}{2}",
  //Nhật ký kiểm định
  GET_AUDIT_BY_STEP: "/api/v2/audit-history/by-step/{0}",
  CREATE_AUDIT: "/api/v2/audit-history",
  EDIT_AUDIT: "/api/v2/audit-history/{0}",
  SEND_FEEDBACK_AUDIT: "/api/v2/audit-history/send-feedback/{0}",
  DELETE_AUDIT: "/api/v2/audit-history/{0}",
  GET_HISTORY_AUDIT_BY_PROCEDURE: "/api/v2/history-sending/by-parcel",
  //Quy trình duyệt
  GET_LIFECYCLE_BY_PARCEL_ID: "/api/v2/lifecycle-division/by-parcel",
  CHANGE_RESULT_LIFECYCLE_DIVISION_BY_ID:
    "/api/v2/lifecycle-division/result/{0}",
  CHANGE_RESULT_INSPECTOR_RECEPTION_BY_ID:
    "/api/v2/lifecycle-inspection/result-reception/{0}",
  //Quy trình kiểm định
  GET_LIFECYCLE_ENDORSER_BY_ID_AND_MY_ORG:
    "/api/v2/lifecycle-inspection/my-org-inpections/by-parcel",
  GET_LIFECYCLE_ENDORSER_BY_ID: "/api/v2/lifecycle-inspection/by-parcel",

  CREATE_NEW_COMMENT_BY_PARCEL_ID: "/api/v2/comment",
  PUBLIC_PARCEL: "/api/v2/public-parcel",
  EDIT_PUBLIC_PARCEL: "/api/v2/public-parcel/{0}",
  GET_PUBLIC_PRODUCT_BY_PARCEL_ID: "/api/v2/public-parcel/by-parcel",
  //COMMENT
  GET_LIST_COMMENT: "/api/v2/comment/list?page={0}&limit={1}{2}",
  GET_COMMENT_BY_PARCEL_ID: "/api/v2/comment/by-parcel",
  UPDATE_COMMENT_BY_ID: "/api/v2/comment/{0}",
  DELETE_CMT_BY_ID: "/api/v2/comment/{0}",
  GET_COMMENT_BY_ME: "//api/v2/comment/by-me",
  //ORGANIZATION
  CREATE_ORG: "/api/v2/org",
  EDIT_ORG: "/api/v2/org/{0}",
  DELETE_ORG: "/api/v2/org/{0}",
  //MANUFACTURE
  GET_ALL_MANUFACTURE_BY_PAGINATION: "/api/v2/org-unit?page={0}&limit={1}{2}",
  GET_ALL_MANUFACTURE_BY_PAGINATION_BY_PARCEL:
    "/api/v2/org-unit?org={0}&page={1}&limit={2}{3}",
  CREATE_MANUFACTURE: "/api/v2/org-unit",
  UPDATE_MANUFACTURE: "/api/v2/org-unit/{0}",
  DELETE_MANUFACTURE: "/api/v2/org-unit/{0}",
  //HISTORY PROCEDURE
  CREATE_RECORD_HISTORY_PROCEDURE: "/api/v2/product-history",
  GET_RECORD_HISTORY_PROCEDURE_BY_STEP: "/api/v2/product-history/by-step",
  UPDATE_PRODUCT_HISTORY_BY_STEP: "/api/v2/product-history/{0}",
};
