export const URL = {
  LOGIN: "/login",
  MENU: {
    DASHBOARD: "/",
    DANH_MUC: "/danh-muc",
    DON_VI: "/don-vi",
    KHOI_PHUC_TAI_KHOAN: "/khoi-phuc-tai-khoan",
    QUAN_LY_NGUOI_DUNG: "/quan-ly-nguoi-dung",
    USER: "/nguoi-dung",
    ROLE: "/vai-tro",
    DU_LIEU_BO_SUNG: "/du-lieu-bo-sung",
    SETTING: "/cai-dat",
    QUY_TRINH: "/quy-trinh",
    TRUY_XUAT_SAN_PHAM: "/truy-xuat-san-pham",
    QUAN_LY: "/manager",
    DANH_SACH_SAN_PHAM: "/danh-sach-san-pham",
    PHAN_QUYEN_VAI_TRO: "/phan-quyen-vai-tro",
    KIEM_DINH_SAN_PHAM: "/kiem-dinh-san-pham",
    DANH_SACH_KIEM_DINH: "/danh-sach-kiem-dinh",
    QUAN_LY_NHAN_VIEN: "/quan-ly-nhan-vien",
    QUAN_LY_TAI_KHOAN_TO_CHUC: "/tai-khoan-to-chuc",
    DANH_SACH_BINH_LUAN: "/danh-sach-binh-luan",
    DANH_SACH_TO_CHUC: "/danh-sach-to-chuc",
    THONG_KE_DOANH_NGHIEP: "/thong-ke-doanh-nghiep",
    CO_SO_SAN_XUAT: "/co-so-san-xuat",
  },
  THONG_TIN_CA_NHAN: "/thong-tin-ca-nhan",
  RESET_PASSWORD: "/reset-password",
  FORGET_PASSWORD: "/forget-password",
  REGISTER: "/register",
  REGISTER_ENTERPRISE: "/register/enterprise",
  REGISTER_INSPECTION: "/register/inspection",
  THEM_MOI_QUY_TRINH: "/quy-trinh-kiem-dinh",
  CHI_TIET_QUY_TRINH_ID: "/chi-tiet-quy-trinh/{0}",
  THEM_MOI_SAN_PHAM: "/them-moi-san-pham",
  CHI_TIET_SAN_PHAM_ID: "/chi-tiet-san-pham/{0}",
  THEM_LO_SAN_PHAM_ID: "/them-lo-san-pham/{0}",
  CHI_TIET_LO_SAN_PHAM_ID: "/chi-tiet-lo-hang/{0}",
  KIEM_DINH_LO_HANG_ID: "/kiem-dinh-lo-hang/{0}",
  LICH_SU_KIEM_DINH_ID: "/lich-su-kiem-dinh/{0}",
  CHI_TIET_BINH_LUAN_ID: "/chi-tiet-binh-luan/{0}",
  DANG_KY_THANH_CONG: "/dang-ky-thanh-cong",
  CHO_XET_DUYET: "/cho-xet-duyet",
  TRUY_XUAT_SAN_PHAM_FOR_GUEST: "/truy-xuat-san-pham",
  TRUY_XUAT_SAN_PHAM: "/truy-xuat-san-pham",
  TRANG_CHU_QUANG_CAO: "/",
  //BASE HYPERLEDGER
  SITE_HYPERLEDGER:
    "http://truyxuat.hdu.edu.vn/blockchain/#/transactions/bd37ae44e2fbad282a12766522579d3fcecd8f0034a0d413f359a0ddaff9bae8/{0}",
  THONG_KE_SAN_PHAM_ID: "/thong-ke-san-pham/{0}",
};
